/* Generated By:JJTree: Do not edit this line. ASTStorDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.uniluebeck.iti.rteasy.frontend;

public
class ASTStorDecl extends SimpleNode {
  public ASTStorDecl(int id) {
    super(id);
  }

  public ASTStorDecl(RTSim_Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RTSim_ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d7cf47706df84c7d5199626de11fc38f (do not edit this line) */
