/* Generated By:JJTree: Do not edit this line. ASTStorDeclList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.uniluebeck.iti.rteasy.frontend;

public
class ASTStorDeclList extends SimpleNode {
  public ASTStorDeclList(int id) {
    super(id);
  }

  public ASTStorDeclList(RTSim_Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RTSim_ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d3bf8fa0093d8772a7eaecdf3dff5b8e (do not edit this line) */
