/* Generated By:JavaCC: Do not edit this line. RTSim_ParserTreeConstants.java Version 5.0 */
package de.uniluebeck.iti.rteasy.frontend;

public interface RTSim_ParserTreeConstants
{
  public int JJTRTPROG = 0;
  public int JJTDECLS = 1;
  public int JJTDECL = 2;
  public int JJTVOID = 3;
  public int JJTREGBUSDECLLIST = 4;
  public int JJTREGBUSDECL = 5;
  public int JJTMEMDECLLIST = 6;
  public int JJTMEMDECL = 7;
  public int JJTSTORDECLLIST = 8;
  public int JJTSTORDECL = 9;
  public int JJTREGARRAYDECLLIST = 10;
  public int JJTREGARRAYDECL = 11;
  public int JJTSTAT_SEQ = 12;
  public int JJTOUTER_PARSTATS = 13;
  public int JJTIF_STAT = 14;
  public int JJTSWITCH_CASE_STAT = 15;
  public int JJTCASELIST = 16;
  public int JJTINNER_PARSTATS = 17;
  public int JJTEXPR = 18;
  public int JJTNUM_CONST = 19;
  public int JJTBIT_SEQ = 20;
  public int JJTSTAT = 21;


  public String[] jjtNodeName = {
    "RtProg",
    "Decls",
    "Decl",
    "void",
    "RegBusDeclList",
    "RegBusDecl",
    "MemDeclList",
    "MemDecl",
    "StorDeclList",
    "StorDecl",
    "RegArrayDeclList",
    "RegArrayDecl",
    "Stat_Seq",
    "Outer_ParStats",
    "If_Stat",
    "Switch_Case_Stat",
    "CaseList",
    "Inner_ParStats",
    "Expr",
    "Num_Const",
    "Bit_Seq",
    "Stat",
  };
}
/* JavaCC - OriginalChecksum=f0ead6589bc9407f341ebe622185eeff (do not edit this line) */
