/* Generated By:JavaCC: Do not edit this line. RTSim_ParserTreeConstants.java Version 5.0 */
package de.uniluebeck.iti.rteasy.frontend;

public interface RTSim_ParserTreeConstants
{
  public int JJTRTPROG = 0;
  public int JJTDECLS = 1;
  public int JJTDECL = 2;
  public int JJTVOID = 3;
  public int JJTREGBUSDECLLIST = 4;
  public int JJTREGBUSDECL = 5;
  public int JJTMEMDECLLIST = 6;
  public int JJTMEMDECL = 7;
  public int JJTREGARRAYDECLLIST = 8;
  public int JJTREGARRAYDECL = 9;
  public int JJTSTAT_SEQ = 10;
  public int JJTOUTER_PARSTATS = 11;
  public int JJTIF_STAT = 12;
  public int JJTSWITCH_CASE_STAT = 13;
  public int JJTCASELIST = 14;
  public int JJTINNER_PARSTATS = 15;
  public int JJTEXPR = 16;
  public int JJTNUM_CONST = 17;
  public int JJTBIT_SEQ = 18;
  public int JJTSTAT = 19;


  public String[] jjtNodeName = {
    "RtProg",
    "Decls",
    "Decl",
    "void",
    "RegBusDeclList",
    "RegBusDecl",
    "MemDeclList",
    "MemDecl",
    "RegArrayDeclList",
    "RegArrayDecl",
    "Stat_Seq",
    "Outer_ParStats",
    "If_Stat",
    "Switch_Case_Stat",
    "CaseList",
    "Inner_ParStats",
    "Expr",
    "Num_Const",
    "Bit_Seq",
    "Stat",
  };
}
/* JavaCC - OriginalChecksum=22095b9a63567b410ab67dbd7ea857fb (do not edit this line) */
