/* Generated By:JavaCC: Do not edit this line. StorageParserConstants.java */
package de.uniluebeck.iti.rteasy.frontend;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface StorageParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BIN_NUM = 6;
  /** RegularExpression Id. */
  int HEX_NUM = 7;
  /** RegularExpression Id. */
  int DEC_NUM = 8;
  /** RegularExpression Id. */
  int COLON = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;
  /** RegularExpression Id. */
  int COMMA = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<BIN_NUM>",
    "<HEX_NUM>",
    "<DEC_NUM>",
    "\":\"",
    "\";\"",
    "\",\"",
  };

}
