/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.desert.gui;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.desert.gui//ControlSignals//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "ControlSignalsTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "right", openAtStartup = false)
@ActionID(category = "Window", id = "org.desert.gui.ControlSignalsTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ControlSignalsAction",
        preferredID = "ControlSignalsTopComponent"
)
@Messages({
    "CTL_ControlSignalsAction=ControlSignals",
    "CTL_ControlSignalsTopComponent=ControlSignals Window",
    "HINT_ControlSignalsTopComponent=This is a ControlSignals window"
})
public final class ControlSignalsTopComponent extends TopComponent {

    public ControlSignalsTopComponent() {
        initComponents();
        setName(Bundle.CTL_ControlSignalsTopComponent());
        setToolTipText(Bundle.HINT_ControlSignalsTopComponent());
    }

    public void setControlSignals(String controlSignals) {
        signalsEditorPane.setText(controlSignals);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signalsScrollPane = new javax.swing.JScrollPane();
        signalsEditorPane = new javax.swing.JEditorPane();

        signalsEditorPane.setEditable(false);
        signalsScrollPane.setViewportView(signalsEditorPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signalsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signalsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane signalsEditorPane;
    private javax.swing.JScrollPane signalsScrollPane;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
